//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivilApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembresiaUsuario
    {
        public int MembresiaUsuarioID { get; set; }
        public Nullable<int> MembresiaID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
    
        public virtual Membresias Membresias { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
