//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivilApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CivilAppEntities : DbContext
    {
        public CivilAppEntities()
            : base("name=CivilAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EstadoUsuario> EstadoUsuario { get; set; }
        public DbSet<Membresias> Membresias { get; set; }
        public DbSet<MembresiaUsuario> MembresiaUsuario { get; set; }
        public DbSet<Paginas> Paginas { get; set; }
        public DbSet<Perfil> Perfil { get; set; }
        public DbSet<PerfilPagina> PerfilPagina { get; set; }
        public DbSet<Proyectos> Proyectos { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
        public DbSet<Niveles> Niveles { get; set; }
    }
}
