//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivilApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Niveles
    {
        public Niveles()
        {
            this.Proyectos = new HashSet<Proyectos>();
        }
    
        public int NivelID { get; set; }
        public Nullable<int> Descripcion { get; set; }
    
        public virtual ICollection<Proyectos> Proyectos { get; set; }
    }
}
