//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivilApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paginas
    {
        public Paginas()
        {
            this.PerfilPagina = new HashSet<PerfilPagina>();
        }
    
        public int PaginaID { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual ICollection<PerfilPagina> PerfilPagina { get; set; }
    }
}
