//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivilApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilPagina
    {
        public int PerfilPaginaID { get; set; }
        public Nullable<int> PerfilID { get; set; }
        public Nullable<int> PaginaID { get; set; }
    
        public virtual Paginas Paginas { get; set; }
        public virtual Perfil Perfil { get; set; }
    }
}
