//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivilApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.MembresiaUsuario = new HashSet<MembresiaUsuario>();
            this.Proyectos = new HashSet<Proyectos>();
        }
    
        public int UsuarioID { get; set; }
        public Nullable<int> PerfilID { get; set; }
        public Nullable<int> EstadoUsuarioID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string UserLogIn { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
    
        public virtual EstadoUsuario EstadoUsuario { get; set; }
        public virtual ICollection<MembresiaUsuario> MembresiaUsuario { get; set; }
        public virtual Perfil Perfil { get; set; }
        public virtual ICollection<Proyectos> Proyectos { get; set; }
    }
}
